# Generated by Django 5.1.7 on 2025-03-26 04:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brunetto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='registration_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='finishedpasta',
            name='finished_pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brunetto.pasta'),
        ),
        migrations.AlterField(
            model_name='finishedpasta',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finishedpasta',
            name='waste',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='inprogresspasta',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_progress_pasta_employees', to='brunetto.employee'),
        ),
        migrations.AlterField(
            model_name='inprogresspasta',
            name='in_progress_pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brunetto.pasta'),
        ),
        migrations.AlterField(
            model_name='inprogresspasta',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pastacooking',
            name='discard',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pastacooking',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasta_cooking_employees', to='brunetto.employee'),
        ),
        migrations.AlterField(
            model_name='pastacooking',
            name='pasta_cooking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brunetto.pasta'),
        ),
        migrations.AlterField(
            model_name='pastacooking',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pastastuffing',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasta_stuffing_employees', to='brunetto.employee'),
        ),
        migrations.AlterField(
            model_name='pastastuffing',
            name='recipes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pastastuffing',
            name='stuffing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brunetto.stuffing'),
        ),
        migrations.CreateModel(
            name='PastaMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.PositiveIntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_usage_employees', to='brunetto.employee')),
                ('production_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta_machine_usages', to='brunetto.productiondailyrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PastaMachinne',
        ),
    ]
